title: RSB Study Group - PEI
description: We talk about the RSB course
author: Bill Charles
email: my@email.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 1926"
logo: /assets/img/logo.png
baseurl: "/rsb-study-group" # the subpath of your site, e.g. /blog
url: "https://froggr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  episodes:
    output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - update_episodes.sh
